---
- name: pnlab
  hosts: localhost
  gather_facts: false # ansible is running and managing the local host
  roles:
    - roles/rsyslog
    - roles/docker
   
  # exercise 2 - doesn't need a specific role, deploying it as a task 
  tasks:
    - name: install NMAP and dependencies
      apt:
        name:
          - python3
          - python3-nmap
          - nmap
        state: present
...
